USE [master]
GO
/****** Object:  Database [Transfer2]    Script Date: 10/22/2015 15:43:55 ******/
CREATE DATABASE [Transfer2] ON  PRIMARY 
( NAME = N'NatalNotes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Transfer2.mdf' , SIZE = 46080KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB ), 
 FILEGROUP [NatalNotesData] 
( NAME = N'NatalNotes_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Transfer2_D.mdf' , SIZE = 256000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB ), 
 FILEGROUP [NatalNotesIndex] 
( NAME = N'NatalNotes_Index', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Transfer2_I.mdf' , SIZE = 167936KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB ), 
 FILEGROUP [NatalNotesText] 
( NAME = N'NatalNotes_Text', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Transfer2_T.mdf' , SIZE = 460800KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'NatalNotes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Transfer2_L.ldf' , SIZE = 63488KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB )
GO
ALTER AUTHORIZATION ON DATABASE::[Transfer2] TO [sa]
GO
ALTER DATABASE [Transfer2] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Transfer2].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [Transfer2] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [Transfer2] SET ANSI_NULLS OFF
GO
ALTER DATABASE [Transfer2] SET ANSI_PADDING OFF
GO
ALTER DATABASE [Transfer2] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [Transfer2] SET ARITHABORT OFF
GO
ALTER DATABASE [Transfer2] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [Transfer2] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [Transfer2] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [Transfer2] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [Transfer2] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [Transfer2] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [Transfer2] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [Transfer2] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [Transfer2] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [Transfer2] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [Transfer2] SET  DISABLE_BROKER
GO
ALTER DATABASE [Transfer2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [Transfer2] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [Transfer2] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [Transfer2] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [Transfer2] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [Transfer2] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [Transfer2] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [Transfer2] SET  READ_WRITE
GO
ALTER DATABASE [Transfer2] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Transfer2] SET  MULTI_USER
GO
ALTER DATABASE [Transfer2] SET PAGE_VERIFY TORN_PAGE_DETECTION
GO
ALTER DATABASE [Transfer2] SET DB_CHAINING OFF
GO
